### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by kilrau** [ConnextProject/rest-api-client#63]

**Comment by aryabhuptani** [comment]
Started tagging this :+1:

**Comment by kilrau** [comment]
Does it make sense to move the rest-api-client into the indra repo too (just like the react client)?

Would avoid the following procedure everytime there is a new indra version available:
- us bumping rest-api-client versions here and in our setup (e.g. today we did https://github.com/connext/rest-api-client/pull/72 & https://github.com/ExchangeUnion/xud-docker/pull/654)
- you tagging a release here

**Comment by rhlsthrm** [comment]
We have talked about this back and forth a lot. We ultimately decided that client implementations don't really belong in the main monorepo. The React one is somewhat of a special case since we use it as a "smoke test".
