### ISSUE TITLE
Change /deposit to return after node accepted deposit

### ISSUE THREAD

**Issue by kilrau** [ConnextProject/rest-api-client#67]
As discussed in https://github.com/ExchangeUnion/xud/issues/1753#issuecomment-663530203  we'd want the deposit call to return after the node accepted the deposit request since the call otherwise can be hanging for several minutes on mainnet. 

Problem: Currently the user needs to be online to actively uninstall the deposit app once the deposit completed (confirmed on-chain). Needs some more thought on how to do that.

**Comment by kilrau** [comment]
Since we can assume connext client staying online in our setup, @sangaman proposed that we could add a new `/incoming-transfer` endpoint that the connext client could hit to inform us about the completed deposit. See https://github.com/ExchangeUnion/xud/issues/1753#issuecomment-668582033

**Comment by rhlsthrm** [comment]
I'm starting work on this: https://github.com/connext/indra/issues/1359

Once that's complete we can use the same subscriber pattern as other events to register a webhook.

**Comment by pedrouid** [comment]
This has been fixed with v7.1.1

Now `/deposit` endpoint will return the transaction hash instead and the completed deposit on the channel can be subscribed with the event name `DEPOSIT_CONFIRMED`
