### ISSUE TITLE
/deposit call return as soon as deposit tx is **broadcasted**

### ISSUE THREAD

**Issue by kilrau** [ConnextProject/rest-api-client#79]
Currently the rest-api client waits for the whole deposit procedure (including mining) to complete before returning, which can result in a hanging `/deposit` call of several minutes on mainnet.
```
  public async deposit(
    params: RouteMethods.PostDepositRequestParams,
  ): Promise<RouteMethods.PostDepositResponse> {
    const client = this.getClient();
    if (params.assetId === AddressZero) {
      delete params.assetId;
    }
    const response = await client.deposit(params);
    return { txhash: response.transaction.hash };
  }
```
We'd need `/deposit` to return as soon as it gets the txhash from the node (which should be upon broadcasting the tx), so we can display it to the user (https://github.com/ExchangeUnion/xud/issues/1753#issuecomment-669037038). This should get the call duration down to some (milli)seconds.

The only drawback of this would be that the caller wouldn't know if the deposit failed, depsite the deposit tx being mined successfully. Since this shouldn't happen in the first place and additionally can be observed in the logs, we think this is ok.

**Comment by kilrau** [comment]
This needs changes on indra side, in our call we agreed that the node should return 2 things from the /deposit call:
1. the txhash
2. a promise that would complete when the deposit has fully completed

(even though we might not be able to use the promise on the rest-api-client, but that's fine)

**Comment by ghost** [comment]
@pedrouid can we make it so that `rest-api-client` pushes xud the `DEPOSIT_CONFIRMED` event with txhash as the body of the request?

**Comment by kilrau** [comment]
> @pedrouid can we make it so that `rest-api-client` pushes xud the `DEPOSIT_CONFIRMED` event with txhash as the body of the request?

Yes, that would be neat! If xud would receive `DEPOSIT_CONFIRMED` event with txhash in a second step, we could trigger some follow up actions with that, like requesting collateral, notifying the user etc. :+1:

**Comment by ghost** [comment]
> @pedrouid can we make it so that `rest-api-client` pushes xud the `DEPOSIT_CONFIRMED` event with txhash as the body of the request?

Nevermind, I forgot that we might be able to already to this using the `/subscribe` endpoint.

**Comment by aryabhuptani** [comment]
@pedrouid @rhlsthrm what (if any) are the changes needed on our end if xud is able to use `/subscribe`?

The base functionality to return immediately is already in place on the client, but not sure what else we need to do on the `rest-api-client`

**Comment by rhlsthrm** [comment]
`/deposit` returns right away now, so there are no more changes needed.
